# Vulnerability Database Configuration
# Copy this file to config.yaml and customize for your environment

# Scanner Configuration
scanner:
  # Default output format: json, html, text
  default_output_format: "html"
  
  # Maximum issues to display per vulnerability
  max_issues_per_vulnerability: 10
  
  # Scan timeout in seconds
  scan_timeout: 300
  
  # File size limit for scanning (bytes)
  max_file_size: 1048576  # 1MB

# Repository Configuration
repositories:
  target_repos:
    - "Ecg-creator/vercel"
    - "Ecg-creator/DigitalMe"  
    - "Ecg-creator/SynergyzeGovernance"
    - "Believers-common-group/The-believers-lobby"
  
  # Exclude patterns (glob)
  exclude_patterns:
    - "node_modules/**"
    - ".git/**"
    - "*.min.js"
    - "vendor/**"
    - "third_party/**"

# Reporting Configuration
reporting:
  # Include code snippets in reports
  include_code_snippets: true
  
  # Maximum length of code snippets
  max_snippet_length: 200
  
  # Enable detailed remediation guidance
  detailed_remediation: true
  
  # Report retention days
  retention_days: 90

# Notification Configuration
notifications:
  # Enable GitHub issue creation for critical/high vulnerabilities
  create_issues: true
  
  # Issue labels to apply
  issue_labels:
    - "security"
    - "vulnerability"
    - "audit"
  
  # Severity threshold for issue creation
  issue_threshold: "high"  # critical, high, medium, low

# ROI Calculation Settings
roi_analysis:
  # Cost models (USD)
  cost_models:
    data_breach_average: 4240000
    compliance_violation_penalty: 500000
    incident_response_cost: 50000
    developer_hourly_rate: 75
    security_specialist_hourly_rate: 125
    business_disruption_hourly_cost: 5000
  
  # Risk multipliers by severity
  risk_multipliers:
    critical: 1.0
    high: 0.7
    medium: 0.3
    low: 0.1
  
  # Prevention effectiveness rate
  prevention_rate: 0.85  # 85% of incidents prevented

# Compliance Standards
compliance:
  # Standards to track
  standards:
    - "SOX"
    - "GDPR"
    - "PCI-DSS"
    - "ISO 27001"
    - "HIPAA"
  
  # Compliance reporting frequency
  reporting_frequency: "quarterly"
  
  # Risk scoring weights
  risk_weights:
    critical_vulnerabilities: 0.4
    high_vulnerabilities: 0.3
    compliance_gaps: 0.2
    remediation_time: 0.1

# Dashboard Configuration  
dashboard:
  # Auto-refresh interval (minutes)
  refresh_interval: 5
  
  # Enable real-time updates
  real_time_updates: true
  
  # Chart data retention (days)
  chart_retention: 30
  
  # Display theme
  theme: "corporate"  # corporate, dark, light

# Advanced Settings
advanced:
  # Enable experimental features
  experimental_features: false
  
  # Custom vulnerability patterns file
  custom_patterns_file: null
  
  # Integration webhook URLs
  webhook_urls: []
  
  # API rate limiting
  api_rate_limit: 100  # requests per hour